# Generated by Django 3.2.5 on 2021-07-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Edition', models.CharField(max_length=50)),
                ('Publication', models.CharField(max_length=100)),
                ('Borrowing_period', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
