# Generated by Django 3.2.5 on 2021-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ImageBook',
            field=models.ImageField(blank=True, null='True', upload_to='photos/%y%m%d'),
            preserve_default='True',
        ),
    ]
