# Generated by Django 3.2.5 on 2021-07-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0002_book_imagebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Edition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='Status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
