# Generated by Django 3.2.5 on 2021-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(default='fds '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='ImageBook',
            field=models.ImageField(blank=True, null='True', upload_to='photos/%y/%m/%d'),
        ),
    ]
