# Generated by Django 3.2.5 on 2021-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0005_auto_20210714_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ImageBook',
            field=models.ImageField(default='555', upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
