# Generated by Django 3.2.5 on 2021-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0006_alter_book_imagebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
