# Generated by Django 3.2.5 on 2021-07-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0008_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='Isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
