# Generated by Django 3.2.5 on 2021-07-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0009_auto_20210714_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Isbn',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
    ]
