# Generated by Django 3.2.5 on 2021-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0010_auto_20210714_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ImageBook',
            field=models.ImageField(upload_to=''),
        ),
    ]
