# Generated by Django 3.2.5 on 2021-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0011_alter_book_imagebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
