# Generated by Django 3.2.5 on 2021-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0014_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(default='TITLE', max_length=50),
            preserve_default=False,
        ),
    ]
