# Generated by Django 3.2.5 on 2021-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapp', '0017_book_borrowing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ImageBook',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
